export const options = [
  'Action',
  'Adventure',
  'Comedy',
  'Drama',
  'Horror',
  'Science Fiction',
  'Fantasy',
  'Thriller',
  'Detective',
  'Crime',
  'Western',
  'War',
  'Romance',
  'Melodrama',
  'Science Fiction',
  'Historical',
  'Biographical',
  'Documentary',
  'Sports',
  'Musical',
  'Film Noir',
  'Comic Book',
  'Animation',
  'Cartoon',
  'Experimental',
  'Mockumentary',
  'Action',
  'Parable',
  'Novella Film',
];
